version: '3'

services:

  client:
    container_name: client
    build: ./client
    volumes:
      - ./client:/usr/app
      - /usr/app/node_modules
    ports:
      - '4000:4000'
    command: npm start
    restart: always
