version: '3'

services:

  api:
    container_name: api
    build: ./api
    volumes:
      - ./api:/app
      - /app/node_modules
    ports:
      - '8000:8000'
    command: npm start
    restart: always

  client:
    container_name: client
    build: ./client
    volumes:
      - ./client:/usr/app
      - /usr/app/node_modules
    ports:
      - '3000:3000'
    command: npm start
    restart: always
    depends_on:
      - api